// Résumé page images (brief §5.6, §6). Images only — never a PDF.
// Regenerated by scripts/resume-to-images.sh; paths are relative to public/.

export type ResumePage = { webp: string; png: string; width: number; height: number }

export const resumeIntro = {
  label: '04 / Résumé',
  title: 'Résumé',
  watermark: 'kshitijchaubey.github.io',
}

export const resumePages: ResumePage[] = [
  { webp: 'resume/page-1.webp', png: 'resume/page-1.png', width: 1654, height: 2339 },
]

export const resumeAlt = (index: number) =>
  `Résumé page ${index + 1} of ${resumePages.length}`
